project:
  type: website

website:
  title: "Andrew Thomas Jones"
  site-url: "https://www.andrewthomasjones.com.au"
  description: "Personal website of Andrew Thomas Jones, a data scientist, statistician, and software engineer."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: Publications.qmd
        text: Publications
      - href: blog.qmd
        text: Posts
  favicon: favicon.svg

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
execute:
  freeze: auto

listing:
  contents: posts
  feed: 
    items: 20
    type: partial
    title: "Blog Title"
    description: "Blog description"
    language: "en"
